/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssistenteRouteImport } from './routes/assistente'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as ContaIndexRouteImport } from './routes/conta/index'
import { Route as ContaFavoritosRouteImport } from './routes/conta/favoritos'
import { Route as ContaPedidosRouteImport } from './routes/conta/pedidos'
import { Route as ContaVeiculosRouteImport } from './routes/conta/veiculos'
import { Route as ProdutoIdRouteImport } from './routes/produto/$id'
import { Route as ProdutosIndexRouteImport } from './routes/produtos/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistenteRoute = AssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaIndexRoute = ContaIndexRouteImport.update({
  id: '/conta/',
  path: '/conta/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaFavoritosRoute = ContaFavoritosRouteImport.update({
  id: '/conta/favoritos',
  path: '/conta/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaPedidosRoute = ContaPedidosRouteImport.update({
  id: '/conta/pedidos',
  path: '/conta/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaVeiculosRoute = ContaVeiculosRouteImport.update({
  id: '/conta/veiculos',
  path: '/conta/veiculos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoIdRoute = ProdutoIdRouteImport.update({
  id: '/produto/$id',
  path: '/produto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosIndexRoute = ProdutosIndexRouteImport.update({
  id: '/produtos/',
  path: '/produtos/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistente': typeof AssistenteRoute
  '/carrinho': typeof CarrinhoRoute
  '/conta/favoritos': typeof ContaFavoritosRoute
  '/conta/pedidos': typeof ContaPedidosRoute
  '/conta/veiculos': typeof ContaVeiculosRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/conta/': typeof ContaIndexRoute
  '/produtos/': typeof ProdutosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistente': typeof AssistenteRoute
  '/carrinho': typeof CarrinhoRoute
  '/conta/favoritos': typeof ContaFavoritosRoute
  '/conta/pedidos': typeof ContaPedidosRoute
  '/conta/veiculos': typeof ContaVeiculosRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/conta': typeof ContaIndexRoute
  '/produtos': typeof ProdutosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistente': typeof AssistenteRoute
  '/carrinho': typeof CarrinhoRoute
  '/conta/favoritos': typeof ContaFavoritosRoute
  '/conta/pedidos': typeof ContaPedidosRoute
  '/conta/veiculos': typeof ContaVeiculosRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/conta/': typeof ContaIndexRoute
  '/produtos/': typeof ProdutosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistente'
    | '/carrinho'
    | '/conta/favoritos'
    | '/conta/pedidos'
    | '/conta/veiculos'
    | '/produto/$id'
    | '/conta/'
    | '/produtos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistente'
    | '/carrinho'
    | '/conta/favoritos'
    | '/conta/pedidos'
    | '/conta/veiculos'
    | '/produto/$id'
    | '/conta'
    | '/produtos'
  id:
    | '__root__'
    | '/'
    | '/assistente'
    | '/carrinho'
    | '/conta/favoritos'
    | '/conta/pedidos'
    | '/conta/veiculos'
    | '/produto/$id'
    | '/conta/'
    | '/produtos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistenteRoute: typeof AssistenteRoute
  CarrinhoRoute: typeof CarrinhoRoute
  ContaFavoritosRoute: typeof ContaFavoritosRoute
  ContaPedidosRoute: typeof ContaPedidosRoute
  ContaVeiculosRoute: typeof ContaVeiculosRoute
  ProdutoIdRoute: typeof ProdutoIdRoute
  ContaIndexRoute: typeof ContaIndexRoute
  ProdutosIndexRoute: typeof ProdutosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistente': {
      id: '/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AssistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta/': {
      id: '/conta/'
      path: '/conta'
      fullPath: '/conta/'
      preLoaderRoute: typeof ContaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta/favoritos': {
      id: '/conta/favoritos'
      path: '/conta/favoritos'
      fullPath: '/conta/favoritos'
      preLoaderRoute: typeof ContaFavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta/pedidos': {
      id: '/conta/pedidos'
      path: '/conta/pedidos'
      fullPath: '/conta/pedidos'
      preLoaderRoute: typeof ContaPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta/veiculos': {
      id: '/conta/veiculos'
      path: '/conta/veiculos'
      fullPath: '/conta/veiculos'
      preLoaderRoute: typeof ContaVeiculosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$id': {
      id: '/produto/$id'
      path: '/produto/$id'
      fullPath: '/produto/$id'
      preLoaderRoute: typeof ProdutoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/': {
      id: '/produtos/'
      path: '/produtos'
      fullPath: '/produtos/'
      preLoaderRoute: typeof ProdutosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistenteRoute: AssistenteRoute,
  CarrinhoRoute: CarrinhoRoute,
  ContaFavoritosRoute: ContaFavoritosRoute,
  ContaPedidosRoute: ContaPedidosRoute,
  ContaVeiculosRoute: ContaVeiculosRoute,
  ProdutoIdRoute: ProdutoIdRoute,
  ContaIndexRoute: ContaIndexRoute,
  ProdutosIndexRoute: ProdutosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
